/** @type {import('tailwindcss').Config} */
export default {
	content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
	darkMode: ['selector', '[data-theme="dark"]'],
	theme: {
		fontFamily: {
			sans: ["'Lexend'", "-apple-system", "BlinkMacSystemFont", "avenir next", "avenir",
				"segoe ui", "helvetica neue", "helvetica", "Cantarell", "Ubuntu", "roboto", "noto", "arial",
				"sans-serif"],
			display: ["'IBM Plex Sans'", "-apple-system", "BlinkMacSystemFont", "avenir next", "avenir",
				"segoe ui", "helvetica neue", "helvetica", "Cantarell", "Ubuntu", "roboto", "noto", "arial",
				"sans-serif"],
			mono: ["'IBM Plex Mono'", "Menlo", "Consolas", "Monaco", "Liberation Mono", "Lucida Console",
				"monospace"],
		},
		fontSize: {
			xs: "0.75rem",
			sm: "0.875rem",
			base: "1rem",
			lg: "1.25rem",
			xl: "1.5rem",
			"2xl": "1.75rem",
			"3xl": "2rem",
			"4xl": "2.25rem",
			"5xl": "2.625rem",
			"6xl": "3rem",
			"7xl": "3.375rem",
			"8xl": "3.75rem",
			"9xl": "4.25rem",
			"10xl": "4.75rem",
			"11xl": "5.25rem",
			"12xl": "5.75rem",
			"13xl": "7.625rem",
			"14xl": "9.75rem",
		},
		lineHeight: {
			"1": "1rem",
			"2": "1.125rem",
			"3": "1.25rem",
			"4": "1.375rem",
			"5": "1.5rem",
			"6": "1.75rem",
			"7": "1.625rem",
			"8": "1.875rem",
			"9": "2.25rem",
			"10": "2.5rem",
			"11": "2.75rem",
			"12": "3.125rem",
			"13": "3.5rem",
			"14": "4rem",
			"15": "4.375rem",
			"16": "4.875rem",
			"17": "5.375rem",
			"18": "5.875rem",
			"19": "6.375rem",
			"20": "8.125rem",
			"21": "10.25rem",
		},
		letterSpacing: {
			"tighter": "-0.96px",
			"tight": "-0.64px",
			"normal": "0px",
			"wide": ".16px",
			"wider": ".32px",
		},
		spacing: {
			'1': '0.125rem',
			'2': '0.25rem',
			'3': '0.5rem',
			'4': '0.75rem',
			'5': '1rem',
			'6': '1.5rem',
			'7': '2rem',
			'8': '2.5rem',
			'9': '3rem',
			'10': '4rem',
			'11': '5rem',
			'12': '6rem',
			'13': '10rem',
		},
		borderWidth: {
			"0": "0px",
			"1": "1px",
			"3": "3px",

		},
		borderRadius: {
			"none": "0px",
			"sm": "0.0625rem",
			DEFAULT: "0.1875rem",
			"md": "0.375rem",
			"lg": "0.5625rem",
			"xl": "0.9375rem",
			"full": "9999px",
		},
		colors: {
			transparent: "transparent",
			background: "var(--color-background)",
			primary: {
				// SOLID VERSIONS
				"1": "var(--accent-1)",
				"2": "var(--accent-2)",
				"3": "var(--accent-3)",
				"4": "var(--accent-4)",
				"5": "var(--accent-5)",
				"6": "var(--accent-6)",
				"7": "var(--accent-7)",
				"8": "var(--accent-8)",
				"9": "var(--accent-9)",
				"10": "var(--accent-10)",
				"11": "var(--accent-11)",
				"12": "var(--accent-12)",
				// ALPHA VERSIONS
				"a1": "var(--accent-a1)",
				"a2": "var(--accent-a2)",
				"a3": "var(--accent-a3)",
				"a4": "var(--accent-a4)",
				"a5": "var(--accent-a5)",
				"a6": "var(--accent-a6)",
				"a7": "var(--accent-a7)",
				"a8": "var(--accent-a8)",
				"a9": "var(--accent-a9)",
				"a10": "var(--accent-a10)",
				"a11": "var(--accent-a11)",
				"a12": "var(--accent-a12)",
				// UTILITY VERSIONS
				"contrast": "var(--accent-contrast)",
				"surface": "var(--accent-surface)",
				"indicator": "var(--accent-indicator)",
				"track": "var(--accent-track)",
			},
			neutral: {
				// SOLID VERSIONS
				"1": "var(--neutral-1)",
				"2": "var(--neutral-2)",
				"3": "var(--neutral-3)",
				"4": "var(--neutral-4)",
				"5": "var(--neutral-5)",
				"6": "var(--neutral-6)",
				"7": "var(--neutral-7)",
				"8": "var(--neutral-8)",
				"9": "var(--neutral-9)",
				"10": "var(--neutral-10)",
				"11": "var(--neutral-11)",
				"12": "var(--neutral-12)",
				// ALPHA VERSIONS
				"a1": "var(--neutral-a1)",
				"a2": "var(--neutral-a2)",
				"a3": "var(--neutral-a3)",
				"a4": "var(--neutral-a4)",
				"a5": "var(--neutral-a5)",
				"a6": "var(--neutral-a6)",
				"a7": "var(--neutral-a7)",
				"a8": "var(--neutral-a8)",
				"a9": "var(--neutral-a9)",
				"a10": "var(--neutral-a10)",
				"a11": "var(--neutral-a11)",
				"a12": "var(--neutral-a12)",
				// UTILITY VERSIONS
				"contrast": "var(--neutral-contrast)",
				"surface": "var(--neutral-surface)",
				"indicator": "var(--neutral-indicator)",
				"track": "var(--neutral-track)",
			},
		},
		screens: {
			"sm": "320px",
			"md": "672px",
			"lg": "1056px",
			"xl": "1312px",
			"2xl": "1584px",
		}
	},
	plugins: []
}
